### ISSUE TITLE
Problem with integration with Keycloak

### ISSUE THREAD

**Issue by gandc66** [linkwarden/linkwarden#1063]
### For installation issues, please visit discord.linkwarden.app

Hello, I have problem with integration linkwarden with Keycloak.

```
linkwarden-1  | [0] [next-auth][error][SIGNIN_OAUTH_ERROR]
linkwarden-1  | [0] https://next-auth.js.org/errors#signin_oauth_error self-signed certificate in certificate chain {
linkwarden-1  | [0]   error: {
linkwarden-1  | [0]     message: 'self-signed certificate in certificate chain',
linkwarden-1  | [0]     stack: 'Error: self-signed certificate in certificate chain\n' +
linkwarden-1  | [0]       '    at TLSSocket.onConnectSecure (node:_tls_wrap:1600:34)\n' +
linkwarden-1  | [0]       '    at TLSSocket.emit (node:events:517:28)\n' +
linkwarden-1  | [0]       '    at TLSSocket._finishInit (node:_tls_wrap:1017:8)\n' +
linkwarden-1  | [0]       '    at ssl.onhandshakedone (node:_tls_wrap:803:12)',
linkwarden-1  | [0]     name: 'Error'
linkwarden-1  | [0]   },
linkwarden-1  | [0]   providerId: 'keycloak',
linkwarden-1  | [0]   message: 'self-signed certificate in certificate chain'
linkwarden-1  | [0] }
```

I`m using self-signed certs, they are signed by my Intermediate CA which itself with my RootCA.
.env:
```
NEXT_PUBLIC_KEYCLOAK_ENABLED=true
KEYCLOAK_CUSTOM_NAME=SSO
KEYCLOAK_ISSUER=https://<changed>/realms/ldap
KEYCLOAK_CLIENT_ID=linkwarden
KEYCLOAK_CLIENT_SECRET=<changed>
```
docker-compose:
```
services:
  postgres:
    image: postgres:16-alpine
    env_file: .env
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  linkwarden:
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
    restart: always
    # build: . # uncomment this line to build from source
    image: ghcr.io/linkwarden/linkwarden:latest # comment this line to build from source
    ports:
      - 3000:3000
    volumes:
      - ./data:/data/data
      - /usr/local/share/ca-certificates:/usr/local/share/ca-certificates:ro
    depends_on:
      - postgres
```
What am I duing wrong? I tryed to add CA to container via
`      - /usr/local/share/ca-certificates:/usr/local/share/ca-certificates:ro`
 and
```
     - ./Intermediate.crt:/etc/ssl/certs/Intermediate.pem
      - ./Root.crt:/etc/ssl/certs/Root.pem
```
