### ISSUE TITLE
Cant Create Account

### ISSUE THREAD

**Issue by Undomeno** [linkwarden/linkwarden#1074]
**Describe the bug**
linkwarden stuck at the creating accout popup after sign up
<img width="517" alt="Image" src="https://github.com/user-attachments/assets/3a6551bf-49bd-408c-a686-30aef2d49eec" />

**To Reproduce**
My docker compose 
```
services:
  linkwarden-db:
    image: postgres:15
    env_file: ./.env
    environment:
      - POSTGRES_USER=linkwarden
      - POSTGRES_DB=linkwarden
      - POSTGRES_PASSWORD=<pass>
    restart: always
    volumes:
      - ./.config/linkwardenpg:/var/lib/postgresql/data

  linkwarden:
    image: ghcr.io/linkwarden/linkwarden:latest
    env_file: ./.env
    environment:
      - DATABASE_URL=postgresql://linkwarden:<pass>@linkwarden-db/linkwarden
    restart: always
    ports:
      - "3435:3000"
    volumes:
      - ./.config/linkwarden:/data/data
    depends_on:
      - linkwarden-db
```
.env configuration
```
NEXTAUTH_URL=http://localhost:3435/api/v1/auth
NEXTAUTH_SECRET=<pass>

# Manual installation database settings
DATABASE_URL=postgresql://linkwarden:<pass>@linkwarden-db/linkwarden

# Docker installation database settings
POSTGRES_PASSWORD=<pass>
```

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser chrome
 - Version latest

**Logs**
```
linkwarden-1  | yarn run v1.22.19
linkwarden-1  | $ /data/node_modules/.bin/prisma migrate deploy
linkwarden-1  | Prisma schema loaded from prisma/schema.prisma
linkwarden-1  | Datasource "db": PostgreSQL database "linkwarden", schema "public" at "linkwarden-db"
linkwarden-1  |
linkwarden-1  | 58 migrations found in prisma/migrations
linkwarden-1  |
linkwarden-1  |
linkwarden-1  | No pending migrations to apply.
linkwarden-1  | Done in 43.33s.
linkwarden-1  | yarn run v1.22.19
linkwarden-1  | $ concurrently -P "next start {@}" "yarn worker:prod" --
linkwarden-1  | [0] - ready started server on 0.0.0.0:3000, url: http://localhost:3000
linkwarden-1  | [1] $ ts-node --transpile-only --skip-project scripts/worker.ts
linkwarden-1  | [1] Initializing application...
linkwarden-1  | [1] Starting RSS polling...
linkwarden-1  | [1] Starting link preservation...
linkwarden-1  | [0] Warning: For production Image Optimization with Next.js, the optional 'sharp' package is strongly recommended. Run 'yarn add sharp', and Next.js will use it automatically for Image Optimization.
linkwarden-1  | [0] Read more: https://nextjs.org/docs/messages/sharp-missing-in-production
```
```
linkwarden-db-1  |
linkwarden-db-1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
linkwarden-db-1  |
linkwarden-db-1  | 2025-03-01 03:57:10.069 UTC [1] LOG:  starting PostgreSQL 15.12 (Debian 15.12-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
linkwarden-db-1  | 2025-03-01 03:57:10.072 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
linkwarden-db-1  | 2025-03-01 03:57:10.072 UTC [1] LOG:  listening on IPv6 address "::", port 5432
linkwarden-db-1  | 2025-03-01 03:57:10.076 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
linkwarden-db-1  | 2025-03-01 03:57:10.131 UTC [28] LOG:  database system was shut down at 2025-03-01 03:56:37 UTC
linkwarden-db-1  | 2025-03-01 03:57:10.219 UTC [1] LOG:  database system is ready to accept connections
linkwarden-db-1  | 2025-03-01 04:02:10.232 UTC [26] LOG:  checkpoint starting: time
linkwarden-db-1  | 2025-03-01 04:02:10.290 UTC [26] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.042 s, sync=0.001 s, total=0.061 s; sync files=2, longest=0.001 s, average=0.001 s; distance=0 kB, estimate=0 kB
```
