### ISSUE TITLE
Using Meilisearch

### ISSUE THREAD

**Issue by jonathan-strange** [linkwarden/linkwarden#1190]
**Is your question related to a problem or code? Please describe.**
I'm trying to determine how to integrate Meilisearch. The "Advanced Search" page states "This feature is only available if you are using [Linkwarden Cloud](https://linkwarden.app/#pricing) or have installed Linkwarden 2.10 or later on your server with Meilisearch set up." but provides no information on how to set it up.

**Describe what you've tried to solve this question**
This is my config but I don't see any index being created

```
services:
  linkwarden-db:
    container_name: linkwarden-db
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - linkwarden-network
  linkwarden:
    container_name: linkwarden
    image: ghcr.io/linkwarden/linkwarden:latest
    environment:
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@linkwarden-db:5432/postgres
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXT_PUBLIC_OLLAMA_ENDPOINT_URL: https://ollama.shadesmar:11434
      MEILISEARCH_HOST: ${MEILISEARCH_HOST}
      MEILISEARCH_KEY: ${MEILISEARCH_KEY}
    restart: unless-stopped
    volumes:
      - ./data:/data/data
    networks:
      - linkwarden-network
    depends_on:
      - linkwarden-db
  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch:latest
    restart: unless-stopped
    volumes:
      - ./meili_data:/meili_data
    environment:
      MEILI_MASTER_KEY: ${MEILISEARCH_KEY}
    ports:
      - "7700:7700"
    networks:
      - linkwarden-network
    depends_on:
      - linkwarden
```

**Include any code or screenshots (if applicable)**
Add any code snippets, error messages, or screenshots that might help others understand your question better.

**Additional context**
Include any additional context or details that might help get a clearer understanding of your question.

**Comment by jonathan-strange** [comment]
I'm using version 2.10.1

**Comment by daniel31x13** [comment]
Hey sorry for the late reply, you _do_ have meilisearch in the docker compose file so it has already pulled it along with the other ones.

To have it enabled you need to set the `MEILI_MASTER_KEY` to a secret random string and restart the container.

**Comment by jonathan-strange** [comment]
Hi, this doesn't seem to be working for me. I've specified a master key and can use it to log in to the Mielesearch dashboard, however I can see that no indexes have been created. I also can't make use of the advanced search features.

**Comment by jonathan-strange** [comment]
Many thanks, I have it up and working now :-). I ended up digging though older commits which led me down the wrong path. Do you think it may be a good idea to include the `MEILI_MASTER_KEY` env var in the [docker-compose.](https://raw.githubusercontent.com/linkwarden/linkwarden/refs/heads/main/docker-compose.yml)? The Meili service is specified so I think it would be consistent. I'll leave around my updated `docker-compose` in case anyone finds it of use.

```
services:
  linkwarden-db:
    container_name: linkwarden-db
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - traefik-public
      - linkwarden-network
    profiles:
      - linkwarden
      - all
  linkwarden:
    container_name: linkwarden
    image: ghcr.io/linkwarden/linkwarden:latest
    environment:
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@linkwarden-db:5432/postgres
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXT_PUBLIC_OLLAMA_ENDPOINT_URL: http://ollama
      OLLAMA_MODEL: qwen3:14b
      MEILI_MASTER_KEY: ${MEILISEARCH_KEY}
    restart: unless-stopped
    volumes:
      - ./data:/data/data
    networks:
      - traefik-public
      - linkwarden-network
      - ai-network
    depends_on:
      - linkwarden-db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.linkwarden.tls=true"
      - "traefik.http.routers.linkwarden.rule=Host(`linkwarden.shadesmar`)"
      - "traefik.http.routers.linkwarden.entrypoints=https"
      - "traefik.http.services.linkwarden.loadbalancer.server.port=3000"
      - "traefik.http.services.linkwarden.loadbalancer.healthcheck.path=/api/v1/logins"
      - "traefik.http.services.linkwarden.loadbalancer.healthcheck.interval=10s"
      - "traefik.http.services.linkwarden.loadbalancer.healthcheck.timeout=3s"
      - "traefik.http.services.linkwarden.loadbalancer.healthcheck.headers.User-Agent=Traefik-Health-Check"
      - "traefik.http.middlewares.linkwarden-timeout.headers.customRequestHeaders.X-Timeout=30"
      - "traefik.http.routers.linkwarden.middlewares=linkwarden-timeout@docker"
      - "traefik.docker.network=traefik-public"
    profiles:
      - linkwarden
      - all
  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch:latest
    restart: unless-stopped
    volumes:
      - ./meili_data:/meili_data
    environment:
      MEILI_MASTER_KEY: ${MEILISEARCH_KEY}
    ports:
      - "7700:7700"
    networks:
      - traefik-public
      - linkwarden-network
    depends_on:
      - linkwarden
    profiles:
      - linkwarden
      - all
```
