### ISSUE TITLE
Mac M1 Error on docker compose up

### ISSUE THREAD

**Issue by christensen143** [linkwarden/linkwarden#121]
I ran into some errors on an M1 and discovered that they were related to docker not using x86_64 for the platform. This is an easy fix. Open the docker-compose.yml file and add the following:

platform: linux/x86_64

The compose file should look like this now:

```
version: "3.5"
services:
  postgres:
    image: postgres
    env_file: .env
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  linkwarden:
    env_file: .env
    platform: linux/x86_64
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
    restart: always
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./data:/data/data
    depends_on:
      - postgres
```
