### ISSUE TITLE
Authentication issue. The new user cannot log in to the website.

### ISSUE THREAD

**Issue by Creogenesis** [linkwarden/linkwarden#157]
**After creating a new user, it is not possible to authenticate using their credentials.**

System: **CentOS**
Method: **Docker Swarm - Portainer**

Own build docker image without any changes.

Message: **Server error. There is a problem with the server configuration. Check the server logs for more information.**

```
version: "3.5"
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - /portainer/linkwarden/pgdata:/var/lib/postgresql/data
  linkwarden:
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/linkwardendb
    image: creogenesis/linkwarden:latest
    ports:
      - 3003:3000
    volumes:
      - /portainer/linkwarden/data:/data/data
    depends_on:
      - postgres
```

Logs:

prisma:query SELECT "public"."User"."id", "public"."User"."name", "public"."User"."username", "public"."User"."email", "public"."User"."emailVerified", "public"."User"."image", "public"."User"."password", "public"."User"."isPrivate", "public"."User"."createdAt" FROM "public"."User" WHERE "public"."User"."username" = $1 LIMIT $2 OFFSET $3

prisma:query BEGIN

prisma:query INSERT INTO "public"."User" ("name","username","password","isPrivate","createdAt") VALUES ($1,$2,$3,$4,$5) RETURNING "public"."User"."id"

prisma:query SELECT "public"."User"."id", "public"."User"."name", "public"."User"."username", "public"."User"."email", "public"."User"."emailVerified", "public"."User"."image", "public"."User"."password", "public"."User"."isPrivate", "public"."User"."createdAt" FROM "public"."User" WHERE "public"."User"."id" = $1 LIMIT $2 OFFSET $3

prisma:query COMMIT

[next-auth][error][NO_SECRET] 

https://next-auth.js.org/errors#no_secret Please define a `secret` in production. MissingSecret [MissingSecretError]: Please define a `secret` in production.

    at assertConfig (/data/node_modules/next-auth/core/lib/assert.js:42:12)

    at AuthHandler (/data/node_modules/next-auth/core/index.js:77:52)

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    at async NextAuthApiHandler (/data/node_modules/next-auth/next/index.js:22:19)

    at async NextAuth._args$ (/data/node_modules/next-auth/next/index.js:106:14) {

  code: 'NO_SECRET'

}

**Comment by daniel31x13** [comment]
Hello @Creogenesis,
Have you set the environment variables properly?
https://docs.linkwarden.app/getting-started/self-hosting#installation

In the root folder (where you see the package.json file…) create a new file named `.env` and paste the following text into it:
```
NEXTAUTH_SECRET=VERY_SENSITIVE_SECRET
POSTGRES_PASSWORD=YOUR_POSTGRES_PASSWORD
NEXTAUTH_URL=http://localhost:3000
```

And make sure to change the variables properly.

**Comment by Creogenesis** [comment]
> Hello @Creogenesis, Have you set the environment variables properly? https://docs.linkwarden.app/getting-started/self-hosting#installation
> 
> In the root folder (where you see the package.json file…) create a new file named `.env` and paste the following text into it:
> 
> ```
> NEXTAUTH_SECRET=VERY_SENSITIVE_SECRET
> POSTGRES_PASSWORD=YOUR_POSTGRES_PASSWORD
> NEXTAUTH_URL=http://localhost:3000
> ```
> 
> And make sure to change the variables properly.

My variables is custom add in portainer (not .env file, look yml):

DATABASE_URL=postgresql://postgres:password@postgres:5432/linkwardendb
NEXTAUTH_SECRET=out openssl rand -base64 32
NEXTAUTH_URL=http://localhost:3003 also 3000
POSTGRES_PASSWORD=password

NEXTAUTH_SECRET=?

**Comment by Creogenesis** [comment]
**The issue was resolved** by adding the variable directly to the docker-compose.yml file.

 - NEXTAUTH_SECRET=out openssl rand -base64 32

```
version: "3.5"
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - /portainer/linkwarden/pgdata:/var/lib/postgresql/data
  linkwarden:
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/linkwardendb
      - NEXTAUTH_SECRET=out openssl rand -base64 32
    image: creogenesis/linkwarden:latest
    ports:
      - 3003:3000
    volumes:
      - /portainer/linkwarden/data:/data/data
    depends_on:
      - postgres
```

**What could that mean?**
