### ISSUE TITLE
[Self-hosted] Can't register user when all fields are filled

### ISSUE THREAD

**Issue by jicho** [linkwarden/linkwarden#244]
**Describe the bug**
Every time I want to create a new user I'm getting the "Please fill out all the fields." error.

Is this a bug, or am I missing/overseeing something?

**To Reproduce**
I've used the following docker-compose:
```
version: '3.5'

services:
  linkwarden:
    container_name: Linkwarden
    environment:
      - DATABASE_URL=postgresql://user:pass@postgres/linkwarden
      - EXTAUTH_SECRET=super-secret
      - NEXTAUTH_URL=http://192.168.1.2:3000
      - NEXT_PUBLIC_EMAIL_PROVIDER=true
      - EMAIL_FROM=my@mail.example
      - EMAIL_SERVER=smtp://172.17.0.1:25
      - PUID=1026
      - PGID=100
      - TZ=Europe/Amsterdam
    restart: unless-stopped  
    image: ghcr.io/linkwarden/linkwarden:main
    ports:
      - 3618:3000
    volumes:
      - /volume1/docker/linkwarden:/data/data
    networks:
      - default
      - postgres.network
networks:
    default:
      driver: bridge
    postgres.network:
      external: true
```

Once everything started I'm clicking on the register page, this page is displaying:
<img width="545" alt="image" src="https://github.com/linkwarden/linkwarden/assets/610740/4c6ddf56-3200-486e-ba6a-ce5a06269759">

I fill in all the fields and as soon as I click Sign Up I'm getting:
<img width="281" alt="image" src="https://github.com/linkwarden/linkwarden/assets/610740/bca3c2b9-cfd3-4f21-a040-7a621b7288cf">

Looking at the code:

```
const checkHasEmptyFields = emailEnabled
    ? !body.password || !body.name || !body.email
    : !body.username || !body.password || !body.name;

  if (checkHasEmptyFields)
    return res
      .status(400)
      .json({ response: "Please fill out all the fields." });
```
Found it in: https://github.com/linkwarden/linkwarden/blob/ad525b8b008a323df14e64a282bb3392fa162cd8/pages/api/auth/register.ts#L29

It looks like it has something to do with the missing email address? When that's the case... How can I get the email address field on the register screen?

**Expected behavior**
I would expect to register an account :)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 117.0.5938.132

**Additional context**
I'm trying to get Linkwarden up and running on a Synology NAS so I can test this pice of (great looking) software.
