### ISSUE TITLE
[Selfhosted] Docker compose with external database usage

### ISSUE THREAD

**Issue by stripwire** [linkwarden/linkwarden#320]
I try to run new Linkwarden instance with `docker compose up` and use /.env/`DATABASE_URL` variable to connect to external psql database. I also disable /.env/`POSTGRES_PASSWORD` with `#`.

<details>
<summary>
.env
</summary>
<code>
NEXTAUTH_SECRET=xxx
NEXTAUTH_URL=http://localhost:3000

\# Manual installation database settings
DATABASE_URL=postgresql://linkwarden:password@127.0.0.1:5432/linkwarden

\# Docker installation database settings
\#POSTGRES_PASSWORD=super_secret_password

\# Additional Optional Settings
PAGINATION_TAKE_COUNT=
STORAGE_FOLDER=
AUTOSCROLL_TIMEOUT=
NEXT_PUBLIC_DISABLE_REGISTRATION=
RE_ARCHIVE_LIMIT=

\# AWS S3 Settings
SPACES_KEY=
SPACES_SECRET=
SPACES_ENDPOINT=
SPACES_BUCKET_NAME=
SPACES_REGION=
SPACES_FORCE_PATH_STYLE=

\# SMTP Settings
NEXT_PUBLIC_EMAIL_PROVIDER=
EMAIL_FROM=
EMAIL_SERVER=

\# Keycloak
NEXT_PUBLIC_KEYCLOAK_ENABLED=
KEYCLOAK_ISSUER=
KEYCLOAK_CLIENT_ID=
KEYCLOAK_CLIENT_SECRET=
</code>
</details>

Now `docker compose up` outputs error:
<details>
<summary>
$ docker compose up
</summary>
<code>
linkwarden-postgres-1    | Error: Database is uninitialized and superuser password is not specified.
linkwarden-postgres-1    |        You must specify POSTGRES_PASSWORD to a non-empty value for the
linkwarden-postgres-1    |        superuser. For example, "-e POSTGRES_PASSWORD=password" on "docker run".
linkwarden-postgres-1    |
linkwarden-postgres-1    |        You may also use "POSTGRES_HOST_AUTH_METHOD=trust" to allow all
linkwarden-postgres-1    |        connections without a password. This is *not* recommended.
linkwarden-postgres-1    |
linkwarden-postgres-1    |        See PostgreSQL documentation about "trust":
linkwarden-postgres-1    |        https://www.postgresql.org/docs/current/auth-trust.html
linkwarden-postgres-1 exited with code 1
linkwarden-linkwarden-1  | yarn run v1.22.19
linkwarden-linkwarden-1  | $ /data/node_modules/.bin/prisma migrate deploy
linkwarden-linkwarden-1  | Prisma schema loaded from prisma/schema.prisma
linkwarden-linkwarden-1  | Datasource "db": PostgreSQL database "postgres", schema "public" at "postgres:5432"
linkwarden-linkwarden-1  |
linkwarden-linkwarden-1  | Error: P1001: Can't reach database server at `postgres`:`5432`
linkwarden-linkwarden-1  |
linkwarden-linkwarden-1  | Please make sure your database server is running at `postgres`:`5432`.
linkwarden-linkwarden-1  | error Command failed with exit code 1.
linkwarden-linkwarden-1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
linkwarden-linkwarden-1 exited with code 1
</code>
</details>

Link from /.env/`DATABASE_URL` works with `psql` command.

Can i run linkwarden docker container with external database?

**Comment by Nillth** [comment]
The docker-compose.yml has two services.
Postgres & Linkwarden
To use a external postgres, you would need to:
- disable(//remove) the Postgres service from the Docker-Compose
- remove the `depends_on: -postgres:` in the linkwarden service.
- update the DATABASE_URL to a valid Postgres deployment.

![image](https://github.com/linkwarden/linkwarden/assets/22066262/3b47c4e7-ee3a-4721-8067-207223c96d1d)

in your `docker compose up` logs, you have two Errors.
- The Postgres Service specified in the docker-compose.yml is failing as `You must specify POSTGRES_PASSWORD to a non-empty value for the superuser.` and 
- Linkwarden does not have a valid DATABASE_URL (hint: 127.0.0.1 is a local address for the container, not a network address for external communication)

**Comment by leni8ec** [comment]
### Example config for `docker-compose.yml` (used in **Portainer**)


``` 
version: "3.5"
services:
  linkwarden:  
    container_name: linkwarden
    image: ghcr.io/linkwarden/linkwarden:latest
    restart: unless-stopped
    volumes:
      - /home/docker/linkwarden/data:/data/data        
    ports:
      - 3000:3000
    environment:
      - NEXTAUTH_URL=http://localhost:3000/api/v1/auth
      - NEXTAUTH_SECRET=some-secret
      - DATABASE_URL=postgresql://postgres:some-passw@postgres:5432/postgres
    depends_on:
      - postgres    
      
  postgres:
    container_name: postgres
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - /home/docker/linkwarden/postgres-data:/var/lib/postgresql/data      
    environment:
      - POSTGRES_PASSWORD=some-passw
```

___
P.S. Environment variables - not work outside the `compose` file in **Portainer** (https://github.com/portainer/portainer/issues/10491)
