### ISSUE TITLE
Keycloak - not working?

### ISSUE THREAD

**Issue by modem7** [linkwarden/linkwarden#360]
**Describe the bug**
I've added the values for Keycloak, but I'm not seeing anything that will allow me to login via keycloak/how it is utilised. 

**To Reproduce**
```yaml
  linkwarden:
    container_name: Linkwarden
    image: ghcr.io/linkwarden/linkwarden:latest
    environment:
      - DATABASE_URL=postgresql://${LINKWRDNDBUSER}:${LINKWRDNDBPASS}@linkwardendb:5432/postgres
      - NEXTAUTH_SECRET=$NEXTAUTHSECRET
      # - NEXTAUTH_URL=https://bookmark.$DOMAINNAME/api/v1/auth
      - NEXTAUTH_URL=https://bookmark.$DOMAINNAME
      - NEXT_PUBLIC_DISABLE_REGISTRATION=false
      - NEXT_PUBLIC_KEYCLOAK_ENABLED=true
      - KEYCLOAK_ISSUER=https://keycloak.mydomain.com/realms/myrealm
      - KEYCLOAK_CLIENT_ID=clientID
      - KEYCLOAK_CLIENT_SECRET=longsecret
    networks:
      pihole:
        ipv4_address: '172.22.0.131'
      isolated:
    ports:
      - 45514:3000
    volumes:
      - $USERDIR/Linkwarden/data:/data/data
    depends_on:
      - linkwardendb
    restart: always
```

**Expected behavior**
Some form of keycloak login button/being able to login using keycloak user credentials

**Screenshots**
![image](https://github.com/linkwarden/linkwarden/assets/4349962/8bf1ee26-c5a7-4961-ae88-48ec9d71fee9)
