### ISSUE TITLE
OAuthCreateAccount error with Keycloak

### ISSUE THREAD

**Issue by modem7** [linkwarden/linkwarden#392]
**Describe the bug**
When trying to login via Keycloak SSO, I'm getting redirected back to the login page. 

![image](https://github.com/linkwarden/linkwarden/assets/4349962/3aab5ffe-7ab2-4ee6-8a91-84a35b467543)

![image](https://github.com/linkwarden/linkwarden/assets/4349962/ce32585a-11a0-4002-83b7-9c6c7309ddc1)

```yaml
  linkwarden:
    container_name: Linkwarden
    image: ghcr.io/linkwarden/linkwarden:latest
    environment:
      - DATABASE_URL=postgresql://${LINKWRDNDBUSER}:${LINKWRDNDBPASS}@linkwardendb:5432/postgres
      - NEXTAUTH_SECRET=$NEXTAUTHSECRET
      - NEXTAUTH_URL=https://bookmark.$DOMAINNAME/api/v1/auth
      # - NEXTAUTH_URL=https://bookmark.$DOMAINNAME
      - NEXT_PUBLIC_DISABLE_REGISTRATION=true
      - NEXT_PUBLIC_KEYCLOAK_ENABLED=true
      - KEYCLOAK_ISSUER=https://auth.mydomain.com/realms/traefik
      - KEYCLOAK_CLIENT_ID=linkwarden
      - KEYCLOAK_CLIENT_SECRET=longsecret
      - KEYCLOAK_CUSTOM_NAME=SSO
    networks:
      pihole:
        ipv4_address: '172.22.0.131'
      isolated:
    ports:
      - 45514:3000
    volumes:
      - $USERDIR/Linkwarden/data:/data/data
    logging:
      driver: "local"
      options:
        max-size: 10m
        max-file: "3"
    labels:
      - autoheal=true
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.linkwarden-rtr.entrypoints=https"
      - "traefik.http.routers.linkwarden-rtr.rule=Host(`bookmark.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.linkwarden-rtr.middlewares=chain-no-auth@file" # No Authentication
      # - "traefik.http.routers.linkwarden-rtr.middlewares=chain-oauth-adminsfile" # Keycloak
      ## HTTP Services
      - "traefik.http.routers.linkwarden-rtr.service=linkwarden-svc"
      - "traefik.http.services.linkwarden-svc.loadbalancer.server.port=3000"
    depends_on:
      - linkwardendb
    restart: always
```

![image](https://github.com/linkwarden/linkwarden/assets/4349962/9ffded46-befc-41bf-8292-167687df6d5b)

**Expected behavior**
For login to occur

**Additional context**
Username on both Keycloak and Linkwarden is the same.
