### ISSUE TITLE
Add link that is not available / not checkable to the app

### ISSUE THREAD

**Issue by falkheiland** [linkwarden/linkwarden#401]
Linkwarden 2.4.7

i'd like to add a link to local resources, which the app is apperantly? not able to connect to (f.i. printer web-ui)

if I am trying to add such a page via webextension or manually in the GUI, I get the following error:

> Something went wrong when retrieving the file size

I am not sure if i am doing something wrong, this is a bug or a possible FR.  I can craft a json file and import such a link just fine, but this is not a comfortable way.

**Comment by daniel31x13** [comment]
Could you add the following line to your environment variables?
```
IGNORE_UNAUTHORIZED_CA=true
```

We had a similar issue in #381 which was solved.

**Comment by falkheiland** [comment]
`"IGNORE_UNAUTHORIZED_CA=true",` is set. i can add https links now (don't know if this was the case before setting the env) but if i want to add a `http:` link i get

> [0] TypeError [ERR_INVALID_PROTOCOL]: Protocol "http:" not supported. Expected "https:"

**Comment by nkgiovannivl** [comment]
Same here, I can not add url links to my local services if those use http

**Comment by falkheiland** [comment]
same in 2.4.8

**Comment by artstar-es** [comment]
It would appear that the issue exists for http links as well. I get the following error noted in the log file when I attempt to add a URL that only has an HTTP flavour.
 TypeError [ERR_INVALID_PROTOCOL]: Protocol "http:" not supported. Expected "https:"

This is in a Kubernetes container (TrueCharts), if that is at all helpful or meaningful.

**Comment by s4msy** [comment]
I started over with linkwarden yesterday, fresh docker-compose install with the 2.4.8 version and got hit by this error, too. I've tested a lot of options and it looks like the: 
`IGNORE_UNAUTHORIZED_CA=true`
works only for "https" links with unauthorized or wrong CA-certs. 

But this doesn't solve the "http" error. It looks like we need an env  flag like:
`ALLOW_HTTP=true`

**Comment by falkheiland** [comment]
> Edit: I think its an enhancement, because some folks always want to add things like http://192.168...

which nothing is wrong with that. if a host listens to that address, than you want to set a bookmark / link to that.
i would even extend that approach to all URIs and suggest to abandon that need for https://

**Comment by daniel31x13** [comment]
Added a new release which fully resolves this issue:
https://github.com/linkwarden/linkwarden/releases/tag/v2.4.9

**Comment by timothy890511** [comment]
> Added a new release which fully resolves this issue: https://github.com/linkwarden/linkwarden/releases/tag/v2.4.9

I'm still experiencing this problem with version 2.4.9.

```
[1] Processing link http://eyny.com/forum.php?view=all for user 1
[1] TypeError [ERR_INVALID_PROTOCOL]: Protocol "http:" not supported. Expected "https:"
[1]     at new NodeError (node:internal/errors:405:5)
[1]     at new ClientRequest (node:_http_client:188:11)
[1]     at request (node:http:100:10)
[1]     at /data/node_modules/node-fetch/lib/index.js:1482:15
[1]     at new Promise (<anonymous>)
[1]     at fetch (/data/node_modules/node-fetch/lib/index.js:1451:9)
[1]     at validateUrlSize (/data/lib/api/validateUrlSize.ts:11:33)
[1]     at /data/lib/api/archiveHandler.ts:43:34
[1]     at archiveHandler (/data/lib/api/archiveHandler.ts:272:9)
[1]     at runNextTicks (node:internal/process/task_queues:60:5) {
[1]   code: 'ERR_INVALID_PROTOCOL'
[1] }
```

This is my `docker-compose.yml`

```yml
version: "3.5"
services:
  linkwarden:
    image: ghcr.io/linkwarden/linkwarden:latest
    container_name: linkwarden
    environment:
      - DATABASE_URL=postgresql://user:password@localhost:5432/linkwarden
      - NEXTAUTH_SECRET=XXX
      - NEXTAUTH_URL=http://localhost:3000/api/v1/auth
      - ARCHIVE_TAKE_COUNT=1
      - IGNORE_UNAUTHORIZED_CA=true
      - SPACES_KEY=XXX
      - SPACES_SECRET=XXX
      - SPACES_ENDPOINT=XXX
      - SPACES_BUCKET_NAME=XXX
      - SPACES_REGION=XXX
    restart: always
    network_mode: "host"
    volumes:
      - ./data:/data/data
    deploy:
      resources:
          limits:
              cpus: '1.5'
              memory: 1.5G
```
