### ISSUE TITLE
error  "Email invalid" when saving settings

### ISSUE THREAD

**Issue by kmorber** [linkwarden/linkwarden#434]
Hello,

i receive the error message "email invalid" when i try to save the settings.

![2024-01-20 10 13 48](https://github.com/linkwarden/linkwarden/assets/1584056/2e3529fd-79c1-40a4-ad31-82f4ba583027)

**Comment by daniel31x13** [comment]
What does your environment variables look like?
You need to build the docker image yourself if you’re setting up the smtp email variables.

**Comment by kmorber** [comment]
NEXT_PUBLIC_EMAIL_PROVIDER=true
EMAIL_FROM=linkwarden@******.***
EMAIL_SERVER=smtp://loadbalancer:25

**Comment by daniel31x13** [comment]
Alright so you need to build the image yourself, use this docker-compose file instead:

```
version: "3.5"
services:
  postgres:
    image: postgres:16-alpine
    env_file: .env
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  linkwarden:
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
    restart: always
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./data:/data/data
    depends_on:
      - postgres
```
