### ISSUE TITLE
Profile Setting doesn't show all Settings

### ISSUE THREAD

**Issue by s4en** [linkwarden/linkwarden#438]
Use Docker Compose File for Linkwarden:

```
version: "3.9"
services:
  db:
    image: postgres
    container_name: Linkwarden-DB
    hostname: linkwarden-db
    mem_limit: 1g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "linkwarden", "-U", "linkwardenuser"]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - linkwardendb:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: linkwarden
      POSTGRES_USER: linkwardenuser
      POSTGRES_PASSWORD: linkwardenpass
      GUID: 0
      PUID: 0
    restart: on-failure:5

  linkwarden:
    image: ghcr.io/linkwarden/linkwarden:main
    container_name: Linkwarden
    hostname: linkwarden
    mem_limit: 2g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    ports:
      - 7461:3000
    volumes:
      - linkwarden:/data/data:rw
    environment:
      DATABASE_URL: postgres://linkwardenuser:linkwardenpass@linkwarden-db:5432/linkwarden
      NEXTAUTH_SECRET: XXXXXXXXXXX
      NEXTAUTH_URL: http://1XXXX
# Additional Optional Settings
#      PAGINATION_TAKE_COUNT: 
#      STORAGE_FOLDER: 
#      AUTOSCROLL_TIMEOUT: 
      NEXT_PUBLIC_DISABLE_REGISTRATION: false #or true
    restart: on-failure:5
    depends_on:
      db:
        condition: service_healthy
volumes:
  linkwarden:
    external: true
  linkwardendb:
    external: true
````
So i don't see all seetings:
![184401 - Window](https://github.com/linkwarden/linkwarden/assets/92207667/daec078e-c4b6-4c48-8c7c-ee14a3a94847)

Thats whta i wanted to see:
![276488872-639d9da8-073e-41fa-ba3f-32b174331ff2](https://github.com/linkwarden/linkwarden/assets/92207667/1519c638-8d42-48fb-9982-e782bf4cc9cc)
