### ISSUE TITLE
Links from printables.com are not saved correctly

### ISSUE THREAD

**Issue by Buddinski88** [linkwarden/linkwarden#448]
**Describe the bug**
I try to save some links from printables.com but I only get the message "Just a moment...".

**To Reproduce**
1. Install via docker-compose.
2. Start the services.
3. Try to save any link from printables.com. For example https://www.printables.com/de/model/440814-print-in-place-beginners-dice-case

**Expected behavior**
I expect that there will be a Title and Screenshot saved.

**Screenshots**

![image](https://github.com/linkwarden/linkwarden/assets/50332516/a1bc0dab-f548-4bc8-8dcd-84dd0d0b5697)

**Desktop (please complete the following information):**
 - Windows 11, Microsoft Edge or MacOS with Safari.

**Additional context**
This is my `docker-compose.yml`

```yaml
version: "3.5"
services:
   linkwarden:
    container_name: linkwarden
    environment:
      - DATABASE_URL=postgresql://${DATABASE_USER}:${DATABASE_PW}@linkwarden-db:5432/${DATABASE_NAME}
      - NEXTAUTH_SECRET=$NEXTAUTH_SECRET
    restart: unless-stopped
    image: ghcr.io/linkwarden/linkwarden:latest
    ports:
     - 3000:3000
    volumes:
      - data:/data/data
    depends_on:
      - postgres
    networks:
      - traefik_proxy
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_proxy"
      ## HTTP Routers
      - "traefik.http.routers.linkwarden-rtr.entrypoints=https"
      - "traefik.http.routers.linkwarden-rtr.rule=Host(`linkwarden.$DOMAINNAME`)"
      - "traefik.http.routers.linkwarden-rtr.tls=true"
      - "traefik.http.routers.linkwarden-rtr.tls.certresolver=cloudflare"
      ## Middlewares
      - "traefik.http.routers.linkwarden-rtr.middlewares=chain-no-auth@file" # For No Authentication
      ## HTTP Services
      - "traefik.http.routers.linkwarden-rtr.service=linkwarden-svc"
      - "traefik.http.services.linkwarden-svc.loadbalancer.server.port=3000"

   postgres:
    container_name: linkwarden-db
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: "${DATABASE_NAME}"
      POSTGRES_PASSWORD: "${DATABASE_PW}"
      POSTGRES_USER: "${DATABASE_USER}"
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - default

volumes:
  data:
    driver: local
    driver_opts:
      type: nfs
      o: "nfsvers=4,addr=$NASIP,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14"
      device: ":$NASPATH/linkwarden"
  db:

networks:
  traefik_proxy:
    external: true
```
