### ISSUE TITLE
Can't Login after user Creation

### ISSUE THREAD

**Issue by tetra-archos** [linkwarden/linkwarden#526]
**Describe the bug**
Can't login after creating a user. New deployment of linkwarden.

**To Reproduce**
1.Install with Docker Compose (see below)
2. Click on Create User
3. Fill in user info
4. Go Back and try to login
5. Get a loading circle saying authenticating that disappears quickly

**Expected behavior**
I should be able to log in with my username and password

**Desktop (please complete the following information):**
 - Client:
   - OS: Windows 10
   - Browser Chrome
 - Server:
   - OS: Debian 12
   - Install Method: Docker Compose

**Additional context**

The user is actually created, as when I try recreating the user it does not let me saying the user already exists

compose.yml

```
version: "3.5"
services:
    linkwarden:
        environment:
            - DATABASE_URL=postgresql://linkwarden:${POSTGRESS_PW}@linkwarden-db:5432/linkwarden-db
            - NEXTAUTH_SECRET=${NEXTAUTH_PW}
            - NEXTAUTH_URL=https://192.168.1.114:3333/api/v1/auth
            # - NEXT_PUBLIC_DISABLE_REGISTRATION=true
        restart: unless-stopped
        image: ghcr.io/linkwarden/linkwarden:latest
        ports:
            - 3333:3000
        volumes:
            - /opt/linkwarden/data:/data/data
        depends_on:
            - linkwarden-db
    linkwarden-db:
        container_name: linkwarden-db
        image: postgres:15
        environment:
            POSTGRES_DB: "linkwarden-db"
            POSTGRES_PASSWORD: ${POSTGRESS_PW}
            POSTGRES_USER: "linkwarden"
        restart: unless-stopped
        volumes:
            - /opt/linkwarden/db:/var/lib/postgresql/data
```
