### ISSUE TITLE
No way to login on login page

### ISSUE THREAD

**Issue by mathieukergosien** [linkwarden/linkwarden#588]
**Is your question related to a problem or code? Please describe.**
 There is no username or password fields on the login page.

**Describe what you've tried to solve this question**
Fresh installation via docker compose
Signed up and created a new account (received user created success notification)
On the sign in page there is no fields where to enter username and password.

Also, the XHR call to http://10.100.0.9:5852/api/v1/auth/session returns an empty Json object.

Tried to add **NEXT_PUBLIC_CREDENTIALS_ENABLED=true** to my env vars but didn't work.

In the _linkwarden-linkwarden-1_ container logs I only see this query getting called regularly:
```
[1] prisma:query SELECT "public"."Link"."id", "public"."Link"."name", "public"."Link"."type", "public"."Link"."description", "public"."Link"."collectionId", "public"."Link"."url", "public"."Link"."textContent", "public"."Link"."preview", "public"."Link"."image", "public"."Link"."pdf", "public"."Link"."readable", "public"."Link"."lastPreserved", "public"."Link"."importDate", "public"."Link"."createdAt", "public"."Link"."updatedAt" FROM "public"."Link" WHERE ("public"."Link"."url" IS NOT NULL AND ("public"."Link"."image" IS NULL OR "public"."Link"."image" = $1 OR "public"."Link"."pdf" IS NULL OR "public"."Link"."pdf" = $2 OR "public"."Link"."readable" IS NULL OR "public"."Link"."readable" = $3)) ORDER BY "public"."Link"."id" DESC LIMIT $4 OFFSET $5
```

Tried browsers: Firefox, Chrome, Edge

**Include any code or screenshots (if applicable)**
Here are my .env vars:

```
NEXTAUTH_SECRET=asecret
NEXTAUTH_URL=http://10.100.0.9:5852/api/v1/auth
NEXT_PUBLIC_CREDENTIALS_ENABLED=true

# Manual installation database settings
#DATABASE_URL=postgresql://user:password@localhost:5432/linkwarden

# Docker installation database settings
POSTGRES_PASSWORD=anothersecret
```

and my compose.yaml:

```
services:
  postgres:
    image: postgres:16-alpine
    env_file: .env
    restart: always
    volumes:
      - /media/Stockage/Data/Linkwarden/Postgres:/var/lib/postgresql/data
  linkwarden:
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
    restart: always
    # build: . # uncomment this line to build from source
    image: ghcr.io/linkwarden/linkwarden:latest # comment this line to build from source
    ports:
      - 5852:3000
    volumes:
      - /media/Stockage/Data/Linkwarden/Data:/data/data
    depends_on:
      - postgres
```

And here is my login page:

![323056207-cfb358ed-1c2a-44a9-8042-42731249a950](https://github.com/linkwarden/linkwarden/assets/37246040/3a8c6e66-748e-4e59-ad66-97a37ce0812e)

**Additional context**
N/A
