### ISSUE TITLE
Links lost titles

### ISSUE THREAD

**Issue by modem7** [linkwarden/linkwarden#662]
**Describe the bug**
Seems that sometime between July 9th and yesterday, all my links have lost their titles in list view.

**To Reproduce**
![image](https://github.com/user-attachments/assets/481c4750-93c7-4a48-b39e-089e42e01ca4)
(latest link I added has a title)

**Expected behavior**
All links to have their titles in all views

**Screenshots**
![image](https://github.com/user-attachments/assets/78e72660-3857-4c93-bd34-b8b7994e8430)

![image](https://github.com/user-attachments/assets/5c2326ed-5c64-463e-b41c-d4333c309639)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Vivaldi (Chrome)
 - Version 6.8.3381.48 (Stable channel) (64-bit) 

**Additional context**
```yaml
  linkwarden:
    container_name: Linkwarden
    image: ghcr.io/linkwarden/linkwarden:latest
    environment:
      - DATABASE_URL=postgresql://${LINKWRDNDBUSER}:${LINKWRDNDBPASS}@linkwardendb:5432/postgres
      - NEXTAUTH_SECRET=$NEXTAUTHSECRET
      - NEXTAUTH_URL=https://bookmark.$DOMAINNAME/api/v1/auth
      - NEXT_PUBLIC_DISABLE_REGISTRATION=true
      - NEXT_PUBLIC_CREDENTIALS_ENABLED=false
      - NEXT_PUBLIC_KEYCLOAK_ENABLED=true
      - KEYCLOAK_ISSUER=$LINKWRDNKCISSUER
      - KEYCLOAK_CLIENT_ID=$LINKWRDNKCCLIENTID
      - KEYCLOAK_CLIENT_SECRET=$LINKWRDNKCCLIENTSECRET
      - KEYCLOAK_CUSTOM_NAME=SSO
    networks:
      pihole:
        ipv4_address: '172.22.0.131'
      isolated:
    ports:
      - 45514:3000
    volumes:
      - $USERDIR/Linkwarden/data:/data/data
    logging:
      driver: "local"
      options:
        max-size: 10m
        max-file: "3"
    labels:
      - autoheal=true
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.linkwarden-rtr.entrypoints=https"
      - "traefik.http.routers.linkwarden-rtr.rule=Host(`bookmark.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.linkwarden-rtr.middlewares=chain-no-auth@file" # No Authentication
      # - "traefik.http.routers.linkwarden-rtr.middlewares=chain-oauth-adminsfile" # Keycloak
      ## HTTP Services
      - "traefik.http.routers.linkwarden-rtr.service=linkwarden-svc"
      - "traefik.http.services.linkwarden-svc.loadbalancer.server.port=3000"
      ## Homepage
      - homepage.name=Linkwarden
      - homepage.group=Other
      - homepage.icon=https://raw.githubusercontent.com/linkwarden/linkwarden/main/assets/logo.png
      - homepage.href=https://bookmark.$DOMAINNAME
    depends_on:
      - linkwardendb
    restart: always

  linkwardendb:
    container_name: LinkwardenDB
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=$LINKWRDNDBPASS
    labels:
      - backup
    logging:
      driver: "local"
      options:
        max-size: 10m
        max-file: "3"
    networks:
      isolated:
    restart: always
    volumes:
      - $USERDIR/Linkwarden/db:/var/lib/postgresql/data
```
