### ISSUE TITLE
sqlite as db in docker version

### ISSUE THREAD

**Issue by mdlaat** [linkwarden/linkwarden#690]
**Is your feature request related to a problem? Please describe.**
for personal use pg does seem to be overkill. In the non docker version of linkwarden, there is a choice for either pg or sqlite as db. See https://github.com/linkwarden/linkwarden/issues/94

**Describe the solution you'd like**
It would be awesome if in the dockerversion of linkwarden one could have the choice for pg or sqlite as the dbase.

**Comment by smartjinyu** [comment]
See #135

**Comment by HudsonAfonso** [comment]
+1

**Comment by moonlight8978** [comment]
I'm facing the same problem, since PostgreSQL is a bit overkill for my home setup

I ended up creating a custom entrypoint and mount it to the container

`entrypoint.sh`
```sh
#!/bin/sh

set -eu

cd packages/prisma
# replace incompatible array type to JSON
sed -i'' -E 's/String\[\][[:space:]]+@default\(\[\]\)/Json @default("[]")/g' schema.prisma
sed -i'' -E 's/Int\[\][[:space:]]+@default\(\[\]\)/Json @default("[]")/g' schema.prisma
# change to provider to sqlite
sed -i'' -E 's/"postgresql"/"sqlite"/g' schema.prisma

rm -rf migrations

yarn prisma migrate deploy
yarn prisma db push

cd /data
# run the service https://github.com/linkwarden/linkwarden/blob/7cec177ef086ffe7932c0b5ef5cf645c043caf8a/Dockerfile#L59
exec yarn concurrently:start
```

`docker-compose.yml`
```yml
services:
  linkwarden:
    image: ghcr.io/linkwarden/linkwarden:v2.11.2
    entrypoint: /entrypoint.sh
    environment:
      DATABASE_URL: "file:/data/data/db.sqlite"
    volumes:
      - ./linkwarden/entrypoint.sh:/entrypoint.sh:ro
      - ./linkwarden/data:/data/data
    ports:
      - 3000:3000
    restart: always
```

it worked well with latest image (v2.11.2) at the moment I tested

// I didn't test the case that the schema got changes, maybe we need to pull the current db state and create initial migration, then create another migration for new updates
