### ISSUE TITLE
Playwright Browser is not installed

### ISSUE THREAD

**Issue by danthonywalker** [linkwarden/linkwarden#709]
**Describe the bug**
Since upgrading to 2.7.1 from 2.6.2 I get the following logs:
```
Error processing link https://gitea.internal.neontech.dev for user 2: browserType.launch: Executable doesn't exist at /.cache/ms-playwright/chromium-1124/chrome-linux/chrome

[1] ╔═════════════════════════════════════════════════════════════════════════╗

[1] ║ Looks like Playwright Test or Playwright was just installed or updated. ║

[1] ║ Please run the following command to download new browsers:              ║

[1] ║                                                                         ║

[1] ║     yarn playwright install                                             ║

[1] ║                                                                         ║

[1] ║ <3 Playwright Team                                                      ║

[1] ╚═════════════════════════════════════════════════════════════════════════╝

[1]     at archiveHandler (/data/lib/api/archiveHandler.ts:47:34)

[1]     at archiveLink (/data/scripts/worker.ts:112:27)

[1]     at /data/scripts/worker.ts:133:17

[1]     at processBatch (/data/scripts/worker.ts:133:6)

[1]     at async init (/data/scripts/worker.ts:148:7) {

[1]   name: 'Error'

[1] }
```

**To Reproduce**
I am using the following compose:
```
services:
  postgres:
    image: library/postgres:16.3
    container_name: linkwarden-postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
  linkwarden:
    image: ghcr.io/linkwarden/linkwarden:v2.7.1
    container_name: linkwarden
    restart: always
    user: 10057:10057
    environment:
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      NEXT_PUBLIC_DISABLE_REGISTRATION: ${NEXT_PUBLIC_DISABLE_REGISTRATION}
      NEXT_PUBLIC_CREDENTIALS_ENABLED: ${NEXT_PUBLIC_CREDENTIALS_ENABLED}
      NEXT_PUBLIC_AUTHENTIK_ENABLED: ${NEXT_PUBLIC_AUTHENTIK_ENABLED}
      AUTHENTIK_ISSUER: ${AUTHENTIK_ISSUER}
      AUTHENTIK_CLIENT_ID: ${AUTHENTIK_CLIENT_ID}
      AUTHENTIK_CLIENT_SECRET: ${AUTHENTIK_CLIENT_SECRET}
    networks:
      - default
      - proxy
    volumes:
      - linkwarden:/data/data
    depends_on:
      - postgres

networks:
  default:
    name: linkwarden
  proxy:
    name: linkwarden-proxy

volumes:
  postgres:
    name: linkwarden-postgres
  linkwarden:
    name: linkwarden
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=address.to.nas,rw
      device: :/mnt/system/linkwarden
```

**Expected behavior**
I believe these logs should not exist. LinkWarden is having a hard time getting previews of the web pages.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
