### ISSUE TITLE
Memory error/double free on 2.7

### ISSUE THREAD

**Issue by drxzcl** [linkwarden/linkwarden#725]
**Describe the bug**

Website stops responding to queries.

Logs contain the following:
```
linkwarden_1  | [0] double free or corruption (out)
linkwarden_1  | [0] free(): corrupted unsorted chunks
linkwarden_1  | [0] Error: socket hang up
linkwarden_1  | [0]     at connResetException (node:internal/errors:720:14)
linkwarden_1  | [0]     at Socket.socketOnEnd (node:_http_client:525:23)
linkwarden_1  | [0]     at Socket.emit (node:events:529:35)
linkwarden_1  | [0]     at endReadableNT (node:internal/streams/readable:1368:12)
linkwarden_1  | [0]     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
linkwarden_1  | [0]   code: 'ECONNRESET'
linkwarden_1  | [0] }
linkwarden_1  | [0] Error: socket hang up
linkwarden_1  | [0]     at connResetException (node:internal/errors:720:14)
linkwarden_1  | [0]     at Socket.socketOnEnd (node:_http_client:525:23)
linkwarden_1  | [0]     at Socket.emit (node:events:529:35)
linkwarden_1  | [0]     at endReadableNT (node:internal/streams/readable:1368:12)
linkwarden_1  | [0]     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
linkwarden_1  | [0]   code: 'ECONNRESET'
linkwarden_1  | [0] }
linkwarden_1  | [0] Error: socket hang up
linkwarden_1  | [0]     at connResetException (node:internal/errors:720:14)
linkwarden_1  | [0]     at Socket.socketOnEnd (node:_http_client:525:23)
linkwarden_1  | [0]     at Socket.emit (node:events:529:35)
linkwarden_1  | [0]     at endReadableNT (node:internal/streams/readable:1368:12)
linkwarden_1  | [0]     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
linkwarden_1  | [0]   code: 'ECONNRESET'
linkwarden_1  | [0] }
```

**To Reproduce**

Deployment in docker container using the following (partial) compose file:

```
version: "3.5"
services:
  postgres:
    image: postgres:16-alpine
    env_file: .env
    restart: always
    networks:
      - web
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  linkwarden:
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
    restart: always
    # build: . # uncomment this line to build from source
    image: ghcr.io/linkwarden/linkwarden:latest # comment this line to build from source
    networks:
      - web
        #ports:
        #- 3000:3000
    volumes:
      - ./data:/data/data
    depends_on:
      - postgres
    labels:
       ....
```

**Expected behavior**
Server keeps responding to requests. No errors about memory corruption in logs.
