### ISSUE TITLE
Unable to use Traefik

### ISSUE THREAD

**Issue by naonak** [linkwarden/linkwarden#773]
Hello,

I'm trying to configure Traefik to access Linkwarden via https://linkwarden.home/. I've configured Adguard to point to Traefik and added the Docker network "linkwarden_traefik" so that Traefik can access Linkwarden (verified). The problem is that after a long loading time, I end up with an error page showing "Bad Gateway" on my browser.

I tried without the environment variable NEXTAUTH_URL_INTERNAL but encountered the same issue. I have checked other tickets mentioning problems with Traefik, but nothing helped. Does anyone have a working solution?

Portainer conf :

```
networks:
  backend:
  traefik: # linkwarden_traefik
services:
  postgres:
    container_name: linkwarden-postgres
    image: postgres:16-alpine
    restart: unless-stopped
    networks:
      backend:
    environment:
      TZ: Europe/Paris
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - /mnt/ssd0/docker-apps/linkwarden/pgdata:/var/lib/postgresql/data
  linkwarden:
    container_name: linkwarden
    image: ghcr.io/linkwarden/linkwarden:latest
    restart: unless-stopped
    env_file:
      - stack.env   
    networks:
      backend:
      traefik:
    ports:
      - 3580:3000
    volumes:
      - /mnt/ssd0/docker-apps/linkwarden/data:/data/data
    depends_on:
      - postgres
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.docker.network=linkwarden_traefik"
      # service
      - "traefik.http.services.linkwarden.loadbalancer.server.port=3000"
      # local
      - "traefik.http.routers.linkwarden-local.rule=Host(`linkwarden.home`)"
      - "traefik.http.routers.linkwarden-local.entrypoints=websecure"
      - "traefik.http.routers.linkwarden-local.service=linkwarden"
      - "traefik.http.routers.linkwarden-local.tls=true"
```
stack.env

```
NEXTAUTH_URL=https://linkwarden.home/api/v1/auth
NEXTAUTH_URL_INTERNAL=http://localhost:3000/api/v1/auth
NEXTAUTH_SECRET=oD9kGEzIQryUf7x3C9L9G5psTzAkuZx3u2i4hE92I1s=
DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
POSTGRES_PASSWORD=E2%CC*!*iz4dqHaVoKv3$Yc3
```
