### ISSUE TITLE
Read-only, rootless docker missing Chrome install which crashes archiveHandler.ts

### ISSUE THREAD

**Issue by genekellyjr** [linkwarden/linkwarden#799]
**Describe the bug**
Running linkwarden as read-only and rootless causes the Chrome install at `/.cache/ms-playwright/chromium-1124/chrome-linux/chrome` to be missing.

**To Reproduce**
`docker-compose.yml`:
```
networks:
    linkwarden-nw:
    linkwarden-internal-nw:
        internal: true

services:
    linkwarden:
        container_name: linkwarden
        # build: . # uncomment this line to build from source
        image: ghcr.io/linkwarden/linkwarden:latest # comment this line to build from source
        environment:
          - DATABASE_URL=postgresql://postgres:${PG_PASS_LINK}@linkwarden-db:5432/postgres
          - PUID=1400
          - PGID=1400
        env_file:
          - .env
        restart: unless-stopped
        ports:
          - "127.0.0.1:3000:3000/tcp"
          - "127.0.0.1:3000:3000/udp"
        volumes:
          - /home/linkwarden/data:/data/data:rw,noexec,nosuid,nodev,Z
        tmpfs:
          - /.cache:uid=1400,gid=1400,rw,noexec,nosuid,nodev
          - /.yarn:uid=1400,gid=1400,rw,noexec,nosuid,nodev
          - /tmp:uid=1400,gid=1400,rw,noexec,nosuid,nodev
          - /data/.next/cache/images:uid=1400,gid=1400,rw,noexec,nosuid,nodev
        depends_on:
          - linkwarden-db
        # Security stuff
        read_only: true
        networks:
          - linkwarden-nw
          - linkwarden-internal-nw
        user: 1400:1400
        security_opt:
          - no-new-privileges:true
        cap_drop:
          - ALL

    linkwarden-db:
        container_name: linkwarden-db
        image: postgres:17-alpine
        restart: unless-stopped
        volumes:
          - /home/linkwarden-db/data:/var/lib/postgresql/data:rw,noexec,nosuid,nodev,Z
        environment:
          - POSTGRES_PASSWORD=${PG_PASS_LINK:?database password required}
          - PUID=1444
          - PGID=1444
        env_file:
          - .env
        # Security stuff
        read_only: true
        # postgres needs below
        tmpfs:
          - /run/postgresql:uid=1444,gid=1444,rw,noexec,nosuid,nodev
          - /tmp:uid=1444,gid=1444,rw,noexec,nosuid,nodev
        networks:
          - linkwarden-internal-nw
        user: 1444:1444
        security_opt:
          - no-new-privileges:true
        cap_drop:
          - ALL
```

Calls to get users set up:
```
sudo useradd -m -u 1400 linkwarden
sudo su - linkwarden bash -c "mkdir -p /home/linkwarden/data
sudo useradd -m -u 1444 linkwarden-db
sudo su - linkwarden-db bash -c "mkdir -p /home/linkwarden-db/data
```

1. `sudo docker compose up -d`
2. Log into Linkwarden
3. Add a link
4. It will spin its wheels trying to archive it.
5. `sudo docker logs linkwarden`
6. See:
```
[1] Processing link <LINK> for user 1
[1] Error processing link <LINK> for user 1: browserType.launch: Executable doesn't exist at /.cache/ms-playwright/chromium-1124/chrome-linux/chrome
[1] ╔═════════════════════════════════════════════════════════════════════════╗
[1] ║ Looks like Playwright Test or Playwright was just installed or updated. ║
[1] ║ Please run the following command to download new browsers:              ║
[1] ║                                                                         ║
[1] ║     yarn playwright install                                             ║
[1] ║                                                                         ║
[1] ║ <3 Playwright Team                                                      ║
[1] ╚═════════════════════════════════════════════════════════════════════════╝
[1]     at archiveHandler (/data/lib/api/archiveHandler.ts:47:34)
[1]     at archiveLink (/data/scripts/worker.ts:112:27)
[1]     at /data/scripts/worker.ts:133:17
[1]     at processBatch (/data/scripts/worker.ts:133:6)
[1]     at async init (/data/scripts/worker.ts:148:7) {
[1]   name: 'Error'
[1] }
```
7. `sudo docker exec -it linkwarden sh`
8. `cd /.cache`
9. `ls`
10. Confirm `ms-playwright` is missing. No visible errors though about its absence.
11. After ~5 minutes this error occurs:
```
[1] /data/lib/api/archiveHandler.ts:28
[1]           new Error(
[1]           ^
[1] Error: Browser has been open for more than 5 minutes.
[1]     at Timeout._onTimeout (/data/lib/api/archiveHandler.ts:28:11)
[1]     at listOnTimeout (node:internal/timers:569:17)
[1]     at processTimers (node:internal/timers:512:7)
[1] error Command failed with exit code 1.
[1] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[1] yarn worker:prod exited with code 1
```
12. After ~10 minutes this error occurs:
```
[0] Error: socket hang up
[0]     at connResetException (node:internal/errors:720:14)
[0]     at Socket.socketOnEnd (node:_http_client:525:23)
[0]     at Socket.emit (node:events:529:35)
[0]     at endReadableNT (node:internal/streams/readable:1368:12)
[0]     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
[0]   code: 'ECONNRESET'
[0] }
[0] Error: socket hang up
[0]     at connResetException (node:internal/errors:720:14)
[0]     at Socket.socketOnEnd (node:_http_client:525:23)
[0]     at Socket.emit (node:events:529:35)
[0]     at endReadableNT (node:internal/streams/readable:1368:12)
[0]     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
[0]   code: 'ECONNRESET'
[0] }
[0] Error: socket hang up
[0]     at connResetException (node:internal/errors:720:14)
[0]     at Socket.socketOnEnd (node:_http_client:525:23)
[0]     at Socket.emit (node:events:529:35)
[0]     at endReadableNT (node:internal/streams/readable:1368:12)
[0]     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
[0]   code: 'ECONNRESET'
[0] }
```
13. Linkwarden just never succeeds at saving the webpage as an archive file.

~~13. Then Linkwarden stops responding at the webui. Needs a restart to work. Docker container does not restart on its own.~~

I fixed the eventual Linkwarden crash by fixing an error about `/data/.next/cache/image` not existing via adding `- /data/.next/cache/images:uid=1400,gid=1400,rw,noexec,nosuid,nodev` to tmpfs (reflected above). Now it's stable long-term, but can't archive.

**Expected behavior**
Linkwarden to be able to archive a webpage with reasonable security settings.

**Server:**
 - Version v2.7.1

**Additional info**
Thanks for making this, it looks perfect - but I need to be able to run it as read-only and rootless.

You may need to replace `127.0.0.1` with your internet connection IP (`ip a` and en##'s IP) if you do not have a reverse proxy on the `linkwarden-nw` pointing to `linkwarden`.
