### ISSUE TITLE
[SOLVED] Password lost in selfhosted installation

### ISSUE THREAD

**Issue by metrolan** [linkwarden/linkwarden#806]
**Is your question related to a problem or code? Please describe.**

I've installed Linkwarden selfthosted and setted up a password for my user. The password was stored in my browser and in my Bitwarden app, so I'm pretty sure it is correct.
Linkwarden is in a VPS using my own domain.
Everything goes fine but suddenly, some months ago Linkwarden didn't recognize the password (Invalid credentials) so I can't login to it.
I have no smtp settings in my .env because I don't know how to put the key to login to gmail.

**Describe what you've tried to solve this question**
Trying other usual passwords just in case. Upgraded the container. Checked steps 1from v1 to v2.

Is there anyway I can delete o overwrite the stored password?

My docker-compose.yml is this:
```
#version: "3.5"
services:
  postgres:
    image: postgres:16-alpine
    env_file: .env
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  linkwarden:
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
    restart: always
    # build: . # uncomment this line to build from source
    image: ghcr.io/linkwarden/linkwarden:latest # comment this line to build from source
    ports:
      - 3000:3000
    volumes:
      - ./data:/data/data
    depends_on:
      - postgres
```
And my .env file is (sensitive information overwrited with *):
```
NEXTAUTH_SECRET=********
NEXTAUTH_URL=http://links.**********.es:3000/api/v1/auth
POSTGRES_PASSWORD=*********
NEXT_PUBLIC_CREDENTIALS_ENABLED=true
```

**Comment by daniel31x13** [comment]
There's a _super_ hacky workaround that I use whenever this happens. I get the hash of an easy password, in this case `11111111` which is `$2b$10$BJ5oURU9.GXDONqKqeuzWuZ8I54BpUWMPiRKQKIqZ.HgWoFJAKdXO`, then I replace the hash with the hash in the database.

Then I login by entering `11111111` as the password and change it to something else from the settings.

**Comment by metrolan** [comment]
> There's a _super_ hacky workaround that I use whenever this happens. I get the hash of an easy password, in this case `11111111` which is `$2b$10$BJ5oURU9.GXDONqKqeuzWuZ8I54BpUWMPiRKQKIqZ.HgWoFJAKdXO`, then I replace the hash with the hash in the database.
> 
> Then I login by entering `11111111` as the password and change it to something else from the settings.

Thank you Daniel. 
I don't know a word about postgre. I'll look for some information but if you can help me a llittle more: Is there an easy way to do that?. What file need to be edited?. There is a lot of stuff in pgdata directory

**Comment by RyanGreenup** [comment]
> There's a _super_ hacky workaround that I use whenever this happens. I get the hash of an easy password, in this case `11111111` which is `$2b$10$BJ5oURU9.GXDONqKqeuzWuZ8I54BpUWMPiRKQKIqZ.HgWoFJAKdXO`, then I replace the hash with the hash in the database.
> 
> Then I login by entering `11111111` as the password and change it to something else from the settings.

Correct me if I'm wrong, we'd need to account for the salt which [10 rounds currently](https://github.com/linkwarden/linkwarden/blob/a71f42af6eb103a439996549a230e083c881dbdb/lib/api/controllers/users/userId/updateUserById.ts#L188), so I thik `1111` would be:


```
$2b$10$c6gjhXoKZQ0Q2LGQ1Z4X5eQOwJEIeGYm9lQNWgUBvgrmPn0yfTm86
```

**Comment by RyanGreenup** [comment]
> > There's a _super_ hacky workaround that I use whenever this happens. I get the hash of an easy password, in this case `11111111` which is `$2b$10$BJ5oURU9.GXDONqKqeuzWuZ8I54BpUWMPiRKQKIqZ.HgWoFJAKdXO`, then I replace the hash with the hash in the database.
> > Then I login by entering `11111111` as the password and change it to something else from the settings.
> 
> Thank you Daniel. I don't know a word about postgre. I'll look for some information but if you can help me a llittle more: Is there an easy way to do that?. What file need to be edited?. There is a lot of stuff in pgdata directory

Here's a walkthrough for anybody that comes across this in the future. I'm going to assume you have a basic understanding of Docker.

I just tested this on my installation and it worked, so hopefully it will work for you too.

To begin with, you won't be able to touch the `pgdata` data directly, you should only interact with the database through `psql`.

## Back everything up

First, back up the database:

```bash
docker compose down
sudo rsync -avh pgdata pgdata.bak
docker compose up -d
```

To restore the data, spin down the containers and copy the backup back to the original location (use `rsync` to preserve the permissions):

## Get the Database Details

First we need the db password, different from the UI password that needs to be reset, and the port it's exposed on.

### The Docker Compose file

Here is my `docker-compose.yml` file:

```yaml
version: "3.5"
services:
  postgres:
    image: postgres:16-alpine
    env_file: .env
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 37194:5432
  linkwarden:
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
    restart: always
    build: . # uncomment this line to build from source
    # image: ghcr.io/linkwarden/linkwarden:latest # comment this line to build from source
    ports:
      - 0.0.0.0:37193:3000
    volumes:
      - ./data:/data/data
    depends_on:
      - postgres
```

### Database Password

In your `docker-compose.yml` file you will have a field called `DATABASE_URL` like so:


```yaml
  linkwarden:
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
```

The `POSTGRES_PASSWORD` variable is set in the `.env`, something like this:

```bash
NEXTAUTH_SECRET=1234
NEXTAUTH_URL=http://localhost:37193/api/v1/auth
POSTGRES_PASSWORD=1234
```
Your password will be different, but you get the idea. The `POSTGRES_PASSWORD` is used in the `DATABASE_URL` field to connect to the database.

### Database Port

You'll also need to make sure the port for the database is exposed:

```
services:
  postgres:
    ports:
      - 37194:5432
```

this may not be the default, I typically expose it so I can get the details with shell scripts (`fzf` and the like)

## Connect to the Database

### Using `psql`

Using this connect to the database, you can run the following command to connect to the database:

```bash
# POSTGRES_PASSWORD=1234
# POSTGRES_USER=postgres
# POSTGRES_DB=postgres
# POSTGRES_PORT=37194
PGPASSWORD=1234 psql -h localhost -p 37194 -U postgres -d postgres
```

Postgres is a bit like a directory of spreadsheet files, each file is a database, and each sheet is a table. List the databases with `\l` and the tables of the connected database with `\dt`. The `-d` flag automatically connected to the `postgres` database so it is sufficient to list the tables with `\dt`.

```sql
\dt
```

```
                List of relations
 Schema |        Name         | Type  |  Owner
--------+---------------------+-------+----------
 public | AccessToken         | table | postgres
 public | Account             | table | postgres
 public | Collection          | table | postgres
 public | Link                | table | postgres
 public | PasswordResetToken  | table | postgres
 public | Subscription        | table | postgres
 public | Tag                 | table | postgres
 public | User                | table | postgres
 public | UsersAndCollections | table | postgres
 public | VerificationToken   | table | postgres
 public | WhitelistedUser     | table | postgres
 public | _LinkToTag          | table | postgres
 public | _LinkToUser         | table | postgres
 public | _prisma_migrations  | table | postgres
(14 rows)
```

### Listing Users

To list all the users and there hashes (`\x` changes the print format), note the use of quotes around `"User"`, which is needed for capital letters:

```sql
\x
select * from "User";
```

```
Expanded display is on.
postgres=# select * from "User";
-[ RECORD 1 ]-----------+-------------------------------------------------------------
id                      | 1
name                    | ryan
username                | ryan
email                   |
emailVerified           |
password                | xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
isPrivate               | f
createdAt               | xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
archiveAsPDF            | t
archiveAsScreenshot     | t
archiveAsWaybackMachine | f
image                   |
updatedAt               | xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
linksRouteTo            | ORIGINAL
collectionOrder         | xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
preventDuplicateLinks   | f
unverifiedNewEmail      |
locale                  | en
archiveAsMonolith       | t

postgres=#
```

### Updating the Password



The hash for `1111` with 10 rounds of salt is used below. the following command sets the hash for the user with the id `1`:

```sql
update "User" set password='$2b$10$C8uRMxJY8J/aGXfZArKCXOGW36P/6ah6NZNjLNRJX2l16jFi0wczO' where id=1;
\x
select * from "User";
```

```
ostgres=# select * from "User";
-[ RECORD 1 ]-----------+-------------------------------------------------------------
id                      | 1
name                    | ryan
username                | ryan
email                   |
emailVerified           |
password                | $2b$10$C8uRMxJY8J/aGXfZArKCXOGW36P/6ah6NZNjLNRJX2l16jFi0wczO
isPrivate               | f
createdAt               | xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
archiveAsPDF            | t
archiveAsScreenshot     | t
archiveAsWaybackMachine | f
image                   |
updatedAt               | xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
linksRouteTo            | ORIGINAL
collectionOrder         | xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
preventDuplicateLinks   | f
unverifiedNewEmail      |
locale                  | en
archiveAsMonolith       | t
```

### Testing the UI

You should now be able to log in with the password `1111`.


## Hashing Passwords

The codebase is using `bcrypt` to hash the password with 10 rounds of salt, so we can get a simple password with the following node script:

```
cd $(mktemp -d)
npm install bcrypt
```

```javascript
 const bcrypt = require('bcrypt');

 const password = "1111";
 const saltRounds = 10;

 const hash = bcrypt.hashSync(password, saltRounds);
 console.log('Password hash:', hash);
```

```bash
node hash.js
```
```
Password hash: $2b$10$C8uRMxJY8J/aGXfZArKCXOGW36P/6ah6NZNjLNRJX2l16jFi0wczO
```

That's how I got the hash for the password above.
