### ISSUE TITLE
Mobile App - Server Settings - My Links

### ISSUE THREAD

**Issue by peterbata** [linkwarden/linkwarden#830]
Mobile device:

1) Apple iPhone 12 Pro / iOS 18.1
2) Installed My Links from the App Store (this is all that came up when I searched for linkwarden)
3) Get started / Chose Self hosted as I have installed Linkwarden from the Community apps in Unraid. It runs as a Docker container.
4) Server route: Connection method = https. / domain = linkwarden.mydomain.com / port =  3000
5) Authentication: Method = Username and password
6) Hit connect. I encounter the follwing error (see screenshot below notes)

Note: I should mention that I use Cloudflare's Zero Trust / Network / Tunnel to create my sub-domain.
Note: I am also using Nginx Proxy Manager where I  setup linkwarden.mydomain.com as a proxy host.
Note: Accessing the web UI from any browser works as expected via https. Connection is secure / Certificate is valid
Note: The only way that I can successfully connect to my self hosted instance is by using my Unraid IP (not ideal)

![Connection Error](https://github.com/user-attachments/assets/09d1b95a-3531-4338-8808-dc3f979f9d55)

Your time and assistance is greatly appreciated.

**Comment by SoCuul** [comment]
@peterbata This app is not related to the linkwarden project. It's made by an independent developer, who has no association with the linkwarden team.

However, I know for sure that cf tunnels work fine with the app as I use them myself (running linkwarden & cf tunnel connector through docker).

My cloudflare tunnel public hostname looks like this:
<img width="441" alt="image" src="https://github.com/user-attachments/assets/c1393d48-0c4b-42f3-9550-22c3de357044">

And my docker compose file looks like this:
```yaml
services:
  postgres:
    container_name: linkwarden-db
    image: postgres:16
    env_file: .env
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
  linkwarden:
    container_name: linkwarden-server
    image: ghcr.io/linkwarden/linkwarden:latest
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./data:/data/data
    depends_on:
      - postgres
volumes:
  pgdata: null
```
