### ISSUE TITLE
Authelia integration is broken in docker

### ISSUE THREAD

**Issue by stanthewizzard** [linkwarden/linkwarden#864]
**Describe the bug**
docker 2.8.3 integration with authelia doesn't work

authelia code

```
- client_id: 'linkwarden'
        client_name: 'linkwarden'
        client_secret: '$pbkdf2-xxxxxxxxxxxxxxxxxxxxxxx'
        public: false
        authorization_policy: 'one_factor'
        consent_mode: implicit
        redirect_uris:
          - 'https://linkwarden.xxxxxxxxxxxxxx.com/api/v1/auth/callback/authelia'
        scopes:
          - 'openid'
          - 'groups'
          - 'profile'
          - 'email'
        userinfo_signed_response_alg: 'none'
```

Linkwarden .env

```
# Authelia
NEXT_PUBLIC_AUTHELIA_ENABLED="true"
AUTHELIA_CLIENT_ID="linkwarden"
AUTHELIA_CLIENT_SECRET="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
AUTHELIA_WELLKNOWN_URL="https://auth.xxxxxxxxxxx.com/.well-known/openid-configuration"
```

`{"error":"invalid_request","error_description":"The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed. The 'redirect_uri' parameter does not match any of the OAuth 2.0 Client's pre-registered 'redirect_uris'."}`

Thanks
