### ISSUE TITLE
Preview images not displaying after moving link to collection

### ISSUE THREAD

**Issue by PhilipJonasFranz** [linkwarden/linkwarden#871]
**Describe the bug**
After adding a link in the "Unorganized" Collection, and moving it to a other collection, the thumbnail of the link is not displayed anymore, and errors are shown both in the container logs, as well as the Browser Console:

Container Logs:

```
[0] Error copying file: [Error: ENOENT: no such file or directory, rename '/data/data/archives/1/5.jpg' -> '/data/data/archives/2/5.jpg'] {
[0]   errno: -2,
[0]   code: 'ENOENT',
[0]   syscall: 'rename',
[0]   path: '/data/data/archives/1/5.jpg',
[0]   dest: '/data/data/archives/2/5.jpg'
[0] }
[0] The requested resource isn't a valid image for /api/v1/archives/5?format=1&preview=true&updatedAt=2024-11-18T12:52:12.151Z received text/plain
```

Browser: 

```
GET | https://linkwarden.mydomain.tld_next/image?url=/api/v1/archives/5format=1&preview=true&updatedAt=2024-11-18T12:52:12.151Z&w=1920&q=75

Results in Code 400:

The requested resource isn't a valid image.
```

Before moving to collection:

![grafik](https://github.com/user-attachments/assets/d5c9f0ec-7dbf-412a-a9a5-74e74f47e82f)

After moving to collection:

![grafik](https://github.com/user-attachments/assets/4d863f80-9fc0-4daa-8227-446fe2f3183d)

On the host where the stack is deployed:

![grafik](https://github.com/user-attachments/assets/00c6d605-9562-41b9-8ada-61651053a570)

Note the difference: `jpg` vs `jpeg` in Container vs on the Host

**To Reproduce**
1. Deploy instance via Docker-Compose and Traefik reverse proxy:

```yml
version: "3.5"

services:
  postgres:
    image: postgres:16-alpine
    env_file: .env
    restart: always
    volumes:
      - ./data/pgdata:/var/lib/postgresql/dat
    networks:
      - internal

  linkwarden:
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
    restart: always
    image: ghcr.io/linkwarden/linkwarden:latest
    volumes:
      - ./data/linkwarden:/data/data
    depends_on:
      - postgres
    networks:
      - internal
      - proxy
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.linkwarden.entrypoints=http"
      - "traefik.http.routers.linkwarden.rule=Host(`linkwarden.mydomain.tld`)"
      - "traefik.http.routers.linkwarden.priority=1000"
      - "traefik.http.middlewares.linkwarden-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.linkwarden.middlewares=linkwarden-https-redirect"

      - "traefik.http.routers.linkwarden-secure.entrypoints=https"
      - "traefik.http.routers.linkwarden-secure.rule=Host(`linkwarden.mydomain.tld`)"
      - "traefik.http.routers.linkwarden-secure.priority=1000"
      - "traefik.http.routers.linkwarden-secure.tls=true"
      - "traefik.http.routers.linkwarden-secure.service=linkwarden"
      - "traefik.http.routers.linkwarden-secure.middlewares=local-whitelist@file, default-headers@file"

      - "traefik.http.services.linkwarden.loadbalancer.server.port=3000"
      
      - "traefik.docker.network=proxy"

networks:
  internal:
  proxy:
    external: true
```

- Register & Login
- Create Link in Unorganized Collection
- Create new Collection
- Move link to new collection via Three Dots -> Edit Link -> Collection
- Image is now gone, errors in Browser Console

**Expected behavior**
The image should be displayed as if the Link were in the "Unorganized" Collection

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Firefox
 - Version 132.0.2 (64-bit)

**Smartphone (please complete the following information):**
 - Not relevant

**Additional context**
- Note `linkwarden.mydomain.tld` is redacted
