### ISSUE TITLE
add a healthcheck to the container image

### ISSUE THREAD

**Issue by landure** [linkwarden/linkwarden#891]
**Is your feature request related to a problem? Please describe.**

Linkwarden container image contains neither wget nor curl. It's possible to setup a healthcheck in JavaScript, but it's not straigthforward.

**Describe the solution you'd like**

Add a healthcheck script to the container image, as described by [Docker Healthcheck for your Node.js App @ Anthony Mineo](https://anthonymineo.com/docker-healthcheck-for-your-node-js-app/).

The example should be adjusted to take into account Linkwarden container environment, possible HTTPS with or without a valid SSL/TLS certificate.

**Describe alternatives you've considered**
An alternative is to add `wget` or `curl` to the container image. It allows for custom healthchecks such as:

```yaml
services
  linkwarden:
    healthcheck:
      test: [ "CMD", "curl", "--silent", "--retry", "0", "--head", "--fail", "http://localhost:3000/" ]
      start_period: 10s
      interval: 60s
      timeout: 3s
      retries: 3
```
