### ISSUE TITLE
How to use a different port that 3000?

### ISSUE THREAD

**Issue by paulr24** [linkwarden/linkwarden#906]
I have successfully deployed via Docker but need to change the port. I have tried editing the stack, changing the port in the following variables, but I'm not able to browse via the new port:

      - NEXTAUTH_URL=http://localhost:3002/api/v1/auth
    ports:
      - 3002:3002

Is there anything further I need to do?

**Comment by SoCuul** [comment]
Since you're mapping the port outside the container, the port inside the container should remain at 3000. Try this compose config:

```yaml
  linkwarden:
    container_name: linkwarden-server
    image: ghcr.io/linkwarden/linkwarden:latest
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
    restart: unless-stopped
    ports:
      - 3002:3000
    volumes:
      - ./data:/data/data
    depends_on:
      - postgres
```
