### ISSUE TITLE
CORS failure for `site.webmanifest` 

### ISSUE THREAD

**Issue by lenaxia** [linkwarden/linkwarden#973]
**Describe the bug**
When spinning up a new instance, and accessing the admin panel, it generates a CORS error trying to access `site.webmanifest`. 

```
Access to manifest at 'https://authelia.domain.tld/?rd=https%3A%2F%2Flink.domain.tld%2Fsite.webmanifest&rm=GET' (redirected from 'https://link.domain.tld/site.webmanifest') from origin 'https://link.domain.tld' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

It looks like that with Linkwarden behind an OIDC provider, the site.webmanifest request gets directed through the provider, and a CORS violation occurs, because the OIDC provider sends a redirect URI back.

Either the dependency on `site.webmanifest` should be removed, since its only used for offline Android access, or instructions for OIDC providers should be updated to indicate that `site.webmanifest` should not be behind authentication and should have bypass rules. 

**To Reproduce**
1. Spin up a new instance with Authelia as SSO (other providers not tested). 
2. Log in
3. Attempt to go to Admin Settings
4. see CORS error

**Expected behavior**
Admin panel loads

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge
 - Version: 131

**Server:**
 - OS: TalosOS v1.9.1, Kubernetes 1.32.0
 - Linkwarden Version: v2.9.1 (ghcr.io/linkwarden/linkwarden)

**Env:***
```
            env:
              - name: NEXTAUTH_URL
                value: https://link.${SECRET_DEV_DOMAIN}/api/v1/auth
              - name: NEXT_PUBLIC_DISABLE_REGISTRATION
                value: true
              - name: NEXT_PUBLIC_CREDENTIALS_ENABLED
                value: false
              - name: STORAGE_FOLDER
                value: "storage" # Will always end up as /data/STOREAGE_FOLDER so eg /data/config
              - name: NEXT_PUBLIC_AUTHELIA_ENABLED
                value: "true"
              - name: AUTHELIA_WELLKNOWN_URL
                value: https://authelia.${SECRET_DEV_DOMAIN}/.well-known/openid-configuration
              - name: HOME
                value: /data/storage
```

**Additional context**
Full browser console logs:
```
Access to manifest at 'https://authelia.domain.tld/?rd=https%3A%2F%2Flink.domain.tld%2Fsite.webmanifest&rm=GET' (redirected from 'https://link.domain.tld/site.webmanifest') from origin 'https://link.domain.tld' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
authelia.domain.tld/?rd=https%3A%2F%2Flink.domain.tld%2Fsite.webmanifest&rm=GET:1 
        
        
        Failed to load resource: net::ERR_FAILED
framework-a2363dd3c3dbe572.js:9  Error: Minified React error #310; visit https://reactjs.org/docs/error-decoder.html?invariant=310 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at aS (framework-a2363dd3c3dbe572.js:9:61465)
    at aI (framework-a2363dd3c3dbe572.js:9:64408)
    at Object.aV [as useEffect] (framework-a2363dd3c3dbe572.js:9:64666)
    at n.useEffect (framework-a2363dd3c3dbe572.js:25:5653)
    at h (_app-d6fe63844e256432.js:24:39302)
    at v (_app-d6fe63844e256432.js:24:39825)
    at o (_app-d6fe63844e256432.js:24:42557)
    at n (admin-8c4bbe8a89eb5cab.js:1:7101)
    at v (admin-8c4bbe8a89eb5cab.js:1:9761)
    at N (admin-8c4bbe8a89eb5cab.js:1:13237)
a5 @ framework-a2363dd3c3dbe572.js:9
main-0aac0628fbd20043.js:1  Error: Minified React error #310; visit https://reactjs.org/docs/error-decoder.html?invariant=310 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at aS (framework-a2363dd3c3dbe572.js:9:61465)
    at aI (framework-a2363dd3c3dbe572.js:9:64408)
    at Object.aV [as useEffect] (framework-a2363dd3c3dbe572.js:9:64666)
    at n.useEffect (framework-a2363dd3c3dbe572.js:25:5653)
    at h (_app-d6fe63844e256432.js:24:39302)
    at v (_app-d6fe63844e256432.js:24:39825)
    at o (_app-d6fe63844e256432.js:24:42557)
    at n (admin-8c4bbe8a89eb5cab.js:1:7101)
    at v (admin-8c4bbe8a89eb5cab.js:1:9761)
    at N (admin-8c4bbe8a89eb5cab.js:1:13237)
ee @ main-0aac0628fbd20043.js:1
main-0aac0628fbd20043.js:1  A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
ee @ main-0aac0628fbd20043.js:1
admin:1  Access to manifest at 'https://authelia.domain.tld/?rd=https%3A%2F%2Flink.domain.tld%2Fsite.webmanifest&rm=GET' (redirected from 'https://link.domain.tld/site.webmanifest') from origin 'https://link.domain.tld' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
authelia.domain.tld/?rd=https%3A%2F%2Flink.domain.tld%2Fsite.webmanifest&rm=GET:1 
        
        
        Failed to load resource: net::ERR_FAILED
[NEW] Explain Console errors by using Copilot in Edge: click
         
         to explain an error. 
        Learn more
        Don't show again
admin:1  Access to internal resource at 'https://authelia.domain.tld/?rd=https%3A%2F%2Flink.domain.tld%2Fsite.webmanifest&rm=GET' (redirected from 'https://link.domain.tld/site.webmanifest') from origin 'https://link.domain.tld' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```
