### ISSUE TITLE
SSO Failing on Authentik (error=OAuthSignin)

### ISSUE THREAD

**Issue by Vaalus** [linkwarden/linkwarden#991]
**Describe the bug**
When choosing to continue with Authentik, the user is redirected to Linkwarden's login screen and the URL gets updated to: https://linkwarden.domain.com/login?callbackUrl=https%3A%2F%2Flinkwarden.domain.com%2Flogin&error=OAuthSignin
**To Reproduce**
1. Click on "Continue with Authentik"
2. Get redirected to Linkwarden's login screen

**Expected behavior**
It should not fail, and then redirect you to Authentik to complete the login process

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Vivaldi
 - Version: 7.0.3495.29 (Stable channel) (64-bit) 

**Smartphone (please complete the following information):**
 - Device: Samsung Z Flip 5
 - OS: Android 14
 - Browser: Brave
 - Version: The latest version

**Additional context**
Thought it was me misconfiguring something in my stack, but all of my other applications work except for Linkwarden. Here are my logs:

```
linkwarden      | [0] [next-auth][error][SIGNIN_OAUTH_ERROR] 
linkwarden      | [0] https://next-auth.js.org/errors#signin_oauth_error self-signed certificate {
linkwarden      | [0]   error: {
linkwarden      | [0]     message: 'self-signed certificate',
linkwarden      | [0]     stack: 'Error: self-signed certificate\n' +
linkwarden      | [0]       '    at TLSSocket.onConnectSecure (node:_tls_wrap:1600:34)\n' +
linkwarden      | [0]       '    at TLSSocket.emit (node:events:517:28)\n' +
linkwarden      | [0]       '    at TLSSocket._finishInit (node:_tls_wrap:1017:8)\n' +
linkwarden      | [0]       '    at ssl.onhandshakedone (node:_tls_wrap:803:12)',
linkwarden      | [0]     name: 'Error'
linkwarden      | [0]   },
linkwarden      | [0]   providerId: 'authentik',
linkwarden      | [0]   message: 'self-signed certificate'
linkwarden      | [0] } 
```

I tried adding NODE_TLS_REJECT_UNAUTHORIZED=0 to my container but was met with the following:

```
[0] (node:147) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
[0] (Use `node --trace-warnings ...` to show where the warning was created)
[0] [next-auth][error][SIGNIN_OAUTH_ERROR]
[0] https://next-auth.js.org/errors#signin_oauth_error expected 200 OK, got: 404 Not Found {
[0]   error: {
[0]     message: 'expected 200 OK, got: 404 Not Found',
[0]     stack: 'OPError: expected 200 OK, got: 404 Not Found\n' +
[0]       '    at processResponse (/data/node_modules/openid-client/lib/helpers/process_response.js:41:11)\n' +
[0]       '    at Issuer.discover (/data/node_modules/openid-client/lib/issuer.js:152:20)\n' +
[0]       '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
[0]       '    at async openidClient (/data/node_modules/next-auth/core/lib/oauth/client.js:16:14)\n' +
[0]       '    at async getAuthorizationUrl (/data/node_modules/next-auth/core/lib/oauth/authorization-url.js:70:18)\n' +
[0]       '    at async Object.signin (/data/node_modules/next-auth/core/routes/signin.js:38:24)\n' +
[0]       '    at async AuthHandler (/data/node_modules/next-auth/core/index.js:260:26)\n' +
[0]       '    at async NextAuthApiHandler (/data/node_modules/next-auth/next/index.js:22:19)\n' +
[0]       '    at async auth (/data/.next/server/pages/api/v1/auth/[...nextauth].js:1666:12)',
[0]     name: 'OPError'
[0]   },
[0]   providerId: 'authentik',
[0]   message: 'expected 200 OK, got: 404 Not Found'
[0] }
```

**Comment by burgerga** [comment]
What is your config? For me Authentik works fine (v2.9.3)...

EDIT: Well, it stopped working for me too with the same error :/

**Comment by jtcleek** [comment]
I was having the same issue. See [this post in #409 ](https://github.com/linkwarden/linkwarden/issues/409#issuecomment-1913411385)

**Comment by Vaalus** [comment]
> I was having the same issue. See [this post in #409 ](https://github.com/linkwarden/linkwarden/issues/409#issuecomment-1913411385)

That did not work unfortunately :(

**Comment by Vaalus** [comment]
> I was having the same issue. See [this post in #409 ](https://github.com/linkwarden/linkwarden/issues/409#issuecomment-1913411385)

Didn't work unfortunately :(

**Comment by AlexanderIBauer** [comment]
None of the linked solutions worked for me. What finally solved this was to ensure the cert was trusted on my host, then map the host certs into the container and tell node to use the system stores via environment variable. During the process I also updated my Authentik containers to the latest version (2025.6.1 from 2024.6.2), but I don't know if that contributed.

Following commonly found instructions, I 
- copied my cert to `/usr/local/share/ca-certificates`
-  ran `sudo update-ca-certificates`
- verified they were linked under `/etc/ssl/certs` and included in the `ca-certificates.crt` file

Then I updated my compose and recreated the container with `docker compose up -d`.

Here is the relevant part of my compose:
```yaml
    volumes:
      - ./data:/data/data
      - /etc/ssl/certs:/etc/ssl/certs:ro # System store
      - /usr/local/share/ca-certificates:/usr/local/share/ca-certificates:ro # Certs will be linked from here, so this also needs to be mounted
    environment:
      ...
      - NEXT_PUBLIC_AUTHENTIK_ENABLED=true
      - NEXTAUTH_URL=*****
      - NEXTAUTH_SECRET=*****
      - AUTHENTIK_ISSUER=*****
      - AUTHENTIK_CLIENT_ID=*****
      - AUTHENTIK_CLIENT_SECRET=*****
      - NODE_OPTIONS=--use-openssl-ca # Add this to use the system store mapped above
```
